### PR TITLE
Just-in-Time Reading of images & events

### PR DESCRIPTION
**Pull request by etienne87**
I find it a bit annoying to have to wait for data to load to inspect a particular video. This P.R proposes to load just-in-time images & events as you go. the sample "viz_all_data" does the visualization of the whole data.

### CODE REVIEW

**Comment by danielgehrig18** [comment]
Hi @etienne87,

Thanks for the cool PR. Can you provide an example on how to run the new visualization script? Thanks!

**Comment by etienne87** [comment]
sure:
```
>> python3 viz_all_data.py /path/to/timelens/hsergb/
```

**Comment by danielgehrig18** [comment]
Just checked and looks good to me. Let me know when you are ready to merge.

**Comment by etienne87** [comment]
if you do not mind the formattings, can you merge?

**Pull request merged**
